FROM ubuntu

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:ondrej/php
RUN apt-get update
RUN apt-get update

RUN apt-get install -y curl \
    composer \
    npm

RUN mkdir /run/php
RUN apt-get install -y php7.3-fpm
RUN apt-get install -y php7.3-mysql \
    php7.3-curl \
    php7.3-intl \
    php7.3-xdebug \
    php7.3-mbstring \
    php7.3-soap \
    php7.3-gd \
    php7.3-bcmath \
    php7.3-zip \
    php7.3-xml \
    php7.3-opcache

RUN apt-get remove -y php7.4-cli
RUN apt-get install -y php-mysql

RUN npm cache clean -f
RUN npm install -g n
RUN n stable

COPY ./ /var/www
WORKDIR /var/www

EXPOSE 8080
RUN npm install -g webpack webpack-cli
RUN npm install

RUN composer install

CMD bash -c "composer serve"
