version: '3.3'
services:
  task:
    build:
      context: ./
      dockerfile: ./dockerfile-dev
    depends_on:
      - db
    restart: always
    command: bash -c "vendor/bin/doctrine orm:schema-tool:create & composer serve & npm run dev && kill $$!"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: $DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - task
      - cnil-pia
    volumes:
      - './:/var/www'
    expose:
      - '8080'
    ports:
      - "8082:8080"

  db:
    image: mysql:8.0.11
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: $DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - task
    expose:
      - '3306'

volumes:
  node_modules:
  vendor:

networks:
  task:
    driver: bridge
  cnil-pia:
    driver: bridge
