<?= $this->doctype() ?>
<html lang="en">
    <head>
        <title>Search movies</title>
        <meta charset="utf-8">
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/vue-select.css'))
        ?>

        <?= $this->inlineScript()->prependFile($this->basePath('index.js')) ?>
    </head>
    <body>
    <div id="app" class="container">
        <?= $this->content ?>
    </div>
    <?= $this->inlineScript() ?>
    </body>
</html>
